### PR TITLE
#12 run testrpc as a daemon

### PR DESCRIPTION
**Pull request by melnikaite**

### CODE REVIEW

**Comment by Ryanmtate** [comment]
Hey @melnikaite 

Thanks for submitting this PR! I didn't know that testrpc could be run as a daemon? Is there a flag that I should be using for this? I tried running the changes above, but the container exited.

Did you have success with this?

I've thought about using pm2 as to fork the process--

**Comment by melnikaite** [comment]
There is no argument for demonizing. In my project I just use & at the end of command.

**Comment by Ryanmtate** [comment]
Interesting. I wasn't able to get the truffle tests working inside the container. Ended up running an external testrpc instance for the testing, but still not able to run `truffle test` inside the container.

Going to leave this open in case a solution is found.

**Comment by Ryanmtate** [comment]
Was able to get the truffle tests to work inside the container. It appeared as if the container was exiting, but after inspecting the travis CI build, I see that it is working... just need to make sure my tests pass now! :)

@melnikaite Thanks for the help! I didn't end up using the `&`, so I am going to close this. I appreciate your taking the time to look at this problem though!!!

screen shot 2017-10-05 at 5 33 09 pm

**Pull request closed without merging**
